// File generated by Manual Extraction (Agent).
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1p1Nr19BosMfFiVi0k82K4-mP0Vw8ceA',
    appId: '1:1010864816996:web:d724e564f78b75b738f071',
    messagingSenderId: '1010864816996',
    projectId: 'computerstudent-a0511',
    authDomain: 'computerstudent-a0511.firebaseapp.com',
    storageBucket: 'computerstudent-a0511.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1p1Nr19BosMfFiVi0k82K4-mP0Vw8ceA',
    appId: '1:1010864816996:android:d724e564f78b75b738f071',
    messagingSenderId: '1010864816996',
    projectId: 'computerstudent-a0511',
    storageBucket: 'computerstudent-a0511.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-lSiWW0OotPnM2JP2Kv-dCkC7sYG9KxM',
    appId: '1:1010864816996:ios:484f10f15734553a38f071',
    messagingSenderId: '1010864816996',
    projectId: 'computerstudent-a0511',
    storageBucket: 'computerstudent-a0511.firebasestorage.app',
    iosBundleId: 'com.shubham.computerapp',
  );
}
